-- Supabase quickstart table (used by apps/web/src/pages/todos.astro)

create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

comment on table public.todos is 'Supabase connection test table. Safe to remove after verifying the client works.';
